{% set name = "plasticparcels" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/oceanparcels/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 9a53047b25c87a9362dcb1dec3c86c009d36f91e3bd61d9f5879e07e7d1cb3d1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - parcels >=3.0.2
    - shapely
    - geopandas

test:
  imports:
    - parcels
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/OceanParcels/plasticparcels
  summary: 'Ready-to-use tool for plastic dispersion simulations and parameterisation development'
  description: |
    plasticparcels is a python package for simulating the transport and dispersion of plastics in the ocean.
    The tool is based on the parcels computational Lagrangian ocean analysis framework,
    providing a modular and customisable collection of methods, notebooks, and tutorials
    for advecting virtual plastic particles with a wide range of physical properties.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://plastic.oceanparcels.org
  dev_url: https://github.com/OceanParcels/plasticparcels

extra:
  recipe-maintainers:
    - erikvansebille
    - michaeldenes
